
#ifndef INTERPRETEUR_H
#define INTERPRETEUR_H

//enum error {MULTIPLE_DEF, MISSING_VAR_NAME, NOT_VALID_NAME, NOT_VALID_TYPE, UNDECLARED_VAR, MISSING_SEMICOLON, NOT_ITERABLE, MISSING_RCRO, INDEX_OUT_OF_BOUNDS, SYNTAX_ERROR, MULTIPLE_TYPES, NOT_EXIST_TYPE, MISSING_RPAR};
//typedef enum error error_e;


void print_help(int argc, char** argv);

#endif
